/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InformationsRouteImport } from './routes/informations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QualificationRouteImport } from './routes/qualification'
import { Route as RapportsRouteImport } from './routes/rapports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationsRoute = InformationsRouteImport.update({
  id: '/informations',
  path: '/informations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationRoute = QualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/informations': typeof InformationsRoute
  '/login': typeof LoginRoute
  '/qualification': typeof QualificationRoute
  '/rapports': typeof RapportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/informations': typeof InformationsRoute
  '/login': typeof LoginRoute
  '/qualification': typeof QualificationRoute
  '/rapports': typeof RapportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/informations': typeof InformationsRoute
  '/login': typeof LoginRoute
  '/qualification': typeof QualificationRoute
  '/rapports': typeof RapportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/documents'
    | '/faq'
    | '/informations'
    | '/login'
    | '/qualification'
    | '/rapports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/documents'
    | '/faq'
    | '/informations'
    | '/login'
    | '/qualification'
    | '/rapports'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/documents'
    | '/faq'
    | '/informations'
    | '/login'
    | '/qualification'
    | '/rapports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  DocumentsRoute: typeof DocumentsRoute
  FaqRoute: typeof FaqRoute
  InformationsRoute: typeof InformationsRoute
  LoginRoute: typeof LoginRoute
  QualificationRoute: typeof QualificationRoute
  RapportsRoute: typeof RapportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informations': {
      id: '/informations'
      path: '/informations'
      fullPath: '/informations'
      preLoaderRoute: typeof InformationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualification': {
      id: '/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof QualificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  DocumentsRoute: DocumentsRoute,
  FaqRoute: FaqRoute,
  InformationsRoute: InformationsRoute,
  LoginRoute: LoginRoute,
  QualificationRoute: QualificationRoute,
  RapportsRoute: RapportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
